spring.application.name=sim-activation-portal

spring.datasource.url=jdbc:mysql://localhost:3306/sim_portal
spring.datasource.username=root
spring.datasource.password=Kajithak@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
